# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(532, 233)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(532, 100))
        MainWindow.setMaximumSize(QtCore.QSize(532, 250))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Ahmed Taha/Desktop/Nvidia Denoiser UI/icons8_cleanup_noise_1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.Start_PB = QtWidgets.QPushButton(self.centralwidget)
        self.Start_PB.setGeometry(QtCore.QRect(370, 160, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Start_PB.setFont(font)
        self.Start_PB.setStyleSheet("#Start_PB {\n"
"background: #ffffff;\n"
"border-radius: 0px;\n"
"border: 3px solid #656565;\n"
"color:black;\n"
"}\n"
"#Start_PB:hover\n"
"{\n"
"border: 5px solid #00BFF3;\n"
"color:#00bff3\n"
"}\n"
"#Start_PB:pressed\n"
"{\n"
" border: 5px solid #656565;\n"
"color:black;\n"
"}")
        self.Start_PB.setObjectName("Start_PB")
        self.input_SrcPth = QtWidgets.QLineEdit(self.centralwidget)
        self.input_SrcPth.setGeometry(QtCore.QRect(100, 40, 331, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_SrcPth.sizePolicy().hasHeightForWidth())
        self.input_SrcPth.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setBold(True)
        font.setWeight(75)
        self.input_SrcPth.setFont(font)
        self.input_SrcPth.setAutoFillBackground(False)
        self.input_SrcPth.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_SrcPth.setClearButtonEnabled(True)
        self.input_SrcPth.setObjectName("input_SrcPth")
        self.label_Src = QtWidgets.QLabel(self.centralwidget)
        self.label_Src.setGeometry(QtCore.QRect(30, 40, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Src.setFont(font)
        self.label_Src.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Src.setObjectName("label_Src")
        self.Top = QtWidgets.QFrame(self.centralwidget)
        self.Top.setGeometry(QtCore.QRect(0, 0, 541, 21))
        self.Top.setMouseTracking(True)
        self.Top.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top.setObjectName("Top")
        self.win_title = QtWidgets.QLabel(self.Top)
        self.win_title.setGeometry(QtCore.QRect(0, 0, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Heavy")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.win_title.setFont(font)
        self.win_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.win_title.setScaledContents(True)
        self.win_title.setAlignment(QtCore.Qt.AlignCenter)
        self.win_title.setOpenExternalLinks(False)
        self.win_title.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.win_title.setObjectName("win_title")
        self.cls_PB = QtWidgets.QPushButton(self.Top)
        self.cls_PB.setGeometry(QtCore.QRect(513, 2, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Heavy")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.cls_PB.setFont(font)
        self.cls_PB.setStyleSheet("#cls_PB {\n"
"background-color:#B70F0F;\n"
"border: none;\n"
"background-repeat: none;\n"
"color: rgb(255, 255, 255);\n"
"font: 87 11pt \"Arca Majora 3 Heavy\";\n"
"border-radius: 4px;\n"
"}\n"
"#cls_PB:hover\n"
"{\n"
"background-color:rgb(229, 0, 4);\n"
"}\n"
"#cls_PB:pressed\n"
"{\n"
"background-color: rgb(160, 0, 0);\n"
"}")
        self.cls_PB.setObjectName("cls_PB")
        self.border_left = QtWidgets.QFrame(self.centralwidget)
        self.border_left.setEnabled(False)
        self.border_left.setGeometry(QtCore.QRect(0, 0, 3, 300))
        self.border_left.setStatusTip("")
        self.border_left.setAccessibleName("")
        self.border_left.setAccessibleDescription("")
        self.border_left.setStyleSheet("border: 3px solid black;")
        self.border_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_left.setObjectName("border_left")
        self.border_right = QtWidgets.QFrame(self.centralwidget)
        self.border_right.setEnabled(False)
        self.border_right.setGeometry(QtCore.QRect(529, 0, 3, 300))
        self.border_right.setStatusTip("")
        self.border_right.setAccessibleName("")
        self.border_right.setAccessibleDescription("")
        self.border_right.setStyleSheet("border: 3px solid black;")
        self.border_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_right.setObjectName("border_right")
        self.border_bottom = QtWidgets.QFrame(self.centralwidget)
        self.border_bottom.setEnabled(False)
        self.border_bottom.setGeometry(QtCore.QRect(0, 230, 532, 3))
        self.border_bottom.setStatusTip("")
        self.border_bottom.setAccessibleName("")
        self.border_bottom.setAccessibleDescription("")
        self.border_bottom.setStyleSheet("border: 3px solid black;")
        self.border_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_bottom.setObjectName("border_bottom")
        self.RB_Custom = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_Custom.setGeometry(QtCore.QRect(190, 170, 111, 19))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.RB_Custom.setFont(font)
        self.RB_Custom.setObjectName("RB_Custom")
        self.RB_Source = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_Source.setGeometry(QtCore.QRect(80, 170, 111, 19))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.RB_Source.setFont(font)
        self.RB_Source.setChecked(True)
        self.RB_Source.setObjectName("RB_Source")
        self.label_AvSp_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_AvSp_2.setGeometry(QtCore.QRect(20, 170, 61, 18))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_AvSp_2.setFont(font)
        self.label_AvSp_2.setObjectName("label_AvSp_2")
        self.Browse_PB = QtWidgets.QPushButton(self.centralwidget)
        self.Browse_PB.setGeometry(QtCore.QRect(440, 40, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Browse_PB.setFont(font)
        self.Browse_PB.setStyleSheet("#Browse_PB {\n"
"background: #ffffff;\n"
"border-radius: 0px;\n"
"border: 1.5px solid #656565;\n"
"color:black;\n"
"}\n"
"#Browse_PB:hover\n"
"{\n"
"border: 2.5px solid #00BFF3;\n"
"color:#00bff3\n"
"}\n"
"#Browse_PB:pressed\n"
"{\n"
" border: 2.5px solid #656565;\n"
"color:black;\n"
"}")
        self.Browse_PB.setObjectName("Browse_PB")
        self.Repeat_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.Repeat_spinBox.setGeometry(QtCore.QRect(80, 200, 42, 22))
        self.Repeat_spinBox.setMinimum(1)
        self.Repeat_spinBox.setObjectName("Repeat_spinBox")
        self.label_AvSp_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_AvSp_3.setGeometry(QtCore.QRect(20, 200, 61, 18))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_AvSp_3.setFont(font)
        self.label_AvSp_3.setObjectName("label_AvSp_3")
        self.label_Busy = QtWidgets.QLabel(self.centralwidget)
        self.label_Busy.setGeometry(QtCore.QRect(340, 130, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Busy.setFont(font)
        self.label_Busy.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Busy.setObjectName("label_Busy")
        self.label_Eng = QtWidgets.QLabel(self.centralwidget)
        self.label_Eng.setGeometry(QtCore.QRect(20, 140, 71, 18))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Eng.setFont(font)
        self.label_Eng.setObjectName("label_Eng")
        self.Eng_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Eng_comboBox.setGeometry(QtCore.QRect(100, 140, 171, 22))
        self.Eng_comboBox.setObjectName("Eng_comboBox")
        self.Eng_comboBox.addItem("")
        self.Eng_comboBox.addItem("")
        self.TestPB = QtWidgets.QPushButton(self.centralwidget)
        self.TestPB.setGeometry(QtCore.QRect(220, 200, 75, 23))
        self.TestPB.setObjectName("TestPB")
        self.Albedo_PB = QtWidgets.QPushButton(self.centralwidget)
        self.Albedo_PB.setGeometry(QtCore.QRect(440, 70, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Albedo_PB.setFont(font)
        self.Albedo_PB.setStyleSheet("#Albedo_PB {\n"
"background: #ffffff;\n"
"border-radius: 0px;\n"
"border: 1.5px solid #656565;\n"
"color:black;\n"
"}\n"
"#Albedo_PB:hover\n"
"{\n"
"border: 2.5px solid #00BFF3;\n"
"color:#00bff3\n"
"}\n"
"#Albedo_PB:pressed\n"
"{\n"
" border: 2.5px solid #656565;\n"
"color:black;\n"
"}")
        self.Albedo_PB.setObjectName("Albedo_PB")
        self.Normal_PB = QtWidgets.QPushButton(self.centralwidget)
        self.Normal_PB.setGeometry(QtCore.QRect(440, 100, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Normal_PB.setFont(font)
        self.Normal_PB.setStyleSheet("#Normal_PB {\n"
"background: #ffffff;\n"
"border-radius: 0px;\n"
"border: 1.5px solid #656565;\n"
"color:black;\n"
"}\n"
"#Normal_PB:hover\n"
"{\n"
"border: 2.5px solid #00BFF3;\n"
"color:#00bff3\n"
"}\n"
"#Normal_PB:pressed\n"
"{\n"
" border: 2.5px solid #656565;\n"
"color:black;\n"
"}")
        self.Normal_PB.setObjectName("Normal_PB")
        self.label_Src_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Src_2.setGeometry(QtCore.QRect(30, 70, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Src_2.setFont(font)
        self.label_Src_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Src_2.setObjectName("label_Src_2")
        self.input_SrcPth_Alb = QtWidgets.QLineEdit(self.centralwidget)
        self.input_SrcPth_Alb.setGeometry(QtCore.QRect(100, 70, 331, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_SrcPth_Alb.sizePolicy().hasHeightForWidth())
        self.input_SrcPth_Alb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setBold(True)
        font.setWeight(75)
        self.input_SrcPth_Alb.setFont(font)
        self.input_SrcPth_Alb.setAutoFillBackground(False)
        self.input_SrcPth_Alb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_SrcPth_Alb.setClearButtonEnabled(True)
        self.input_SrcPth_Alb.setObjectName("input_SrcPth_Alb")
        self.label_Src_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Src_3.setGeometry(QtCore.QRect(30, 100, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Src_3.setFont(font)
        self.label_Src_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Src_3.setObjectName("label_Src_3")
        self.input_SrcPth_Nrm = QtWidgets.QLineEdit(self.centralwidget)
        self.input_SrcPth_Nrm.setGeometry(QtCore.QRect(100, 100, 331, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_SrcPth_Nrm.sizePolicy().hasHeightForWidth())
        self.input_SrcPth_Nrm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setBold(True)
        font.setWeight(75)
        self.input_SrcPth_Nrm.setFont(font)
        self.input_SrcPth_Nrm.setAutoFillBackground(False)
        self.input_SrcPth_Nrm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_SrcPth_Nrm.setClearButtonEnabled(True)
        self.input_SrcPth_Nrm.setObjectName("input_SrcPth_Nrm")
        self.border_left.raise_()
        self.Top.raise_()
        self.Start_PB.raise_()
        self.input_SrcPth.raise_()
        self.label_Src.raise_()
        self.border_right.raise_()
        self.border_bottom.raise_()
        self.RB_Custom.raise_()
        self.RB_Source.raise_()
        self.label_AvSp_2.raise_()
        self.Browse_PB.raise_()
        self.Repeat_spinBox.raise_()
        self.label_AvSp_3.raise_()
        self.label_Busy.raise_()
        self.label_Eng.raise_()
        self.Eng_comboBox.raise_()
        self.TestPB.raise_()
        self.Albedo_PB.raise_()
        self.Normal_PB.raise_()
        self.label_Src_2.raise_()
        self.input_SrcPth_Alb.raise_()
        self.label_Src_3.raise_()
        self.input_SrcPth_Nrm.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_Src.setBuddy(self.input_SrcPth)
        self.label_AvSp_2.setBuddy(self.RB_Source)
        self.label_AvSp_3.setBuddy(self.Repeat_spinBox)
        self.label_Eng.setBuddy(self.input_SrcPth)
        self.label_Src_2.setBuddy(self.input_SrcPth)
        self.label_Src_3.setBuddy(self.input_SrcPth)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.input_SrcPth, self.Browse_PB)
        MainWindow.setTabOrder(self.Browse_PB, self.RB_Source)
        MainWindow.setTabOrder(self.RB_Source, self.RB_Custom)
        MainWindow.setTabOrder(self.RB_Custom, self.Repeat_spinBox)
        MainWindow.setTabOrder(self.Repeat_spinBox, self.Start_PB)
        MainWindow.setTabOrder(self.Start_PB, self.cls_PB)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ray tracing Denoiser"))
        self.Start_PB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Start denoising</p></body></html>"))
        self.Start_PB.setText(_translate("MainWindow", "START"))
        self.input_SrcPth.setToolTip(_translate("MainWindow", "<html><head/><body><p>source image path</p></body></html>"))
        self.label_Src.setToolTip(_translate("MainWindow", "<html><head/><body><p>source image</p></body></html>"))
        self.label_Src.setText(_translate("MainWindow", "Source"))
        self.win_title.setText(_translate("MainWindow", "Ray tracing Denoiser"))
        self.cls_PB.setText(_translate("MainWindow", "x"))
        self.RB_Custom.setToolTip(_translate("MainWindow", "<html><head/><body><p>output to a specific location</p></body></html>"))
        self.RB_Custom.setText(_translate("MainWindow", "Specify Location"))
        self.RB_Custom.setShortcut(_translate("MainWindow", "K"))
        self.RB_Source.setToolTip(_translate("MainWindow", "<html><head/><body><p>output to the same folder as the source image</p></body></html>"))
        self.RB_Source.setText(_translate("MainWindow", "Source Folder"))
        self.RB_Source.setShortcut(_translate("MainWindow", "M"))
        self.label_AvSp_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>The average transfer speed</p></body></html>"))
        self.label_AvSp_2.setText(_translate("MainWindow", "output:"))
        self.Browse_PB.setToolTip(_translate("MainWindow", "<html><head/><body><p>browse for source image</p></body></html>"))
        self.Browse_PB.setText(_translate("MainWindow", "Browse"))
        self.Repeat_spinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>repeat calculation that many times</p></body></html>"))
        self.label_AvSp_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>used to reapply the ai many times</p></body></html>"))
        self.label_AvSp_3.setText(_translate("MainWindow", "Repeat"))
        self.label_Busy.setToolTip(_translate("MainWindow", "<html><head/><body><p>Please Wait, the program is running</p></body></html>"))
        self.label_Busy.setText(_translate("MainWindow", "Denoising, please wait!"))
        self.label_Eng.setToolTip(_translate("MainWindow", "<html><head/><body><p>source image</p></body></html>"))
        self.label_Eng.setText(_translate("MainWindow", "AI Engine"))
        self.Eng_comboBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Which AI Engine to use:</p><p>NVIDIA Optix - for NVIDIA Turing enabled systems, runs much faster.</p><p>Intel Open Image Denoise - for Intel enabled systems, runs slower, but is compatible with almost all systems.</p><p>Each one produces slightly different result.</p></body></html>"))
        self.Eng_comboBox.setItemText(0, _translate("MainWindow", "NVIDIA Optix"))
        self.Eng_comboBox.setItemText(1, _translate("MainWindow", "Intel Open Image Denoise"))
        self.TestPB.setText(_translate("MainWindow", "test"))
        self.Albedo_PB.setToolTip(_translate("MainWindow", "<html><head/><body><p>browse for source image</p></body></html>"))
        self.Albedo_PB.setText(_translate("MainWindow", "Browse"))
        self.Normal_PB.setToolTip(_translate("MainWindow", "<html><head/><body><p>browse for source image</p></body></html>"))
        self.Normal_PB.setText(_translate("MainWindow", "Browse"))
        self.label_Src_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>source image</p></body></html>"))
        self.label_Src_2.setText(_translate("MainWindow", "Albedo"))
        self.input_SrcPth_Alb.setToolTip(_translate("MainWindow", "<html><head/><body><p>source image path</p></body></html>"))
        self.label_Src_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>source image</p></body></html>"))
        self.label_Src_3.setText(_translate("MainWindow", "Normal"))
        self.input_SrcPth_Nrm.setToolTip(_translate("MainWindow", "<html><head/><body><p>source image path</p></body></html>"))
import Resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
